// Generated by delombok at Sat Jul 14 04:26:21 CEST 2018
/*
 * SK's Minecraft Launcher
 * Copyright (C) 2010-2014 Albert Pham <http://www.sk89q.com> and contributors
 * Please see LICENSE.txt for license information.
 */
package moe.nikky.voodoo.format.modpack.entry

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.Transient
import moe.nikky.voodoo.format.modpack.Condition

@Serializable
data class FileInstall(
    var version: String? = null,
    var hash: String,
    var location: String,
    var to: String,
    var side: Side = Side.BOTH,

    var size: Long = 0,

    // TODO: flip it.. define folder / files to be strictly defined by the pack
    // everything else is modifiable

    // userFiels are files that ca be modified by users and will not be downloaded when the hash changes
    var userFile: Boolean = false,

//    var manifest: Manifest? = null,
    @SerialName("when")
    var condition: Condition? = null
) {
    // TODO: add extract type ?
    //  when do we extract / overwrite then ?
    var type: String = "file"

    // alias for "to"
    @Transient
    val targetPath: String
        get() = this.to
}
