// Generated by delombok at Sat Jul 14 04:26:21 CEST 2018
/*
 * SK's Minecraft Launcher
 * Copyright (C) 2010-2014 Albert Pham <http://www.sk89q.com> and contributors
 * Please see LICENSE.txt for license information.
 */
package com.skcraft.launcher.model.loader;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown = true)
public class InstallData {
    private String path;
    private String filePath;

    @SuppressWarnings("all")
    public InstallData() {
    }

    @SuppressWarnings("all")
    public String getPath() {
        return this.path;
    }

    @SuppressWarnings("all")
    public String getFilePath() {
        return this.filePath;
    }

    @SuppressWarnings("all")
    public void setPath(final String path) {
        this.path = path;
    }

    @SuppressWarnings("all")
    public void setFilePath(final String filePath) {
        this.filePath = filePath;
    }

    @Override
    @SuppressWarnings("all")
    public boolean equals(final Object o) {
        if (o == this) return true;
        if (!(o instanceof InstallData)) return false;
        final InstallData other = (InstallData) o;
        if (!other.canEqual((Object) this)) return false;
        final Object this$path = this.getPath();
        final Object other$path = other.getPath();
        if (this$path == null ? other$path != null : !this$path.equals(other$path)) return false;
        final Object this$filePath = this.getFilePath();
        final Object other$filePath = other.getFilePath();
        if (this$filePath == null ? other$filePath != null : !this$filePath.equals(other$filePath)) return false;
        return true;
    }

    @SuppressWarnings("all")
    protected boolean canEqual(final Object other) {
        return other instanceof InstallData;
    }

    @Override
    @SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final Object $path = this.getPath();
        result = result * PRIME + ($path == null ? 43 : $path.hashCode());
        final Object $filePath = this.getFilePath();
        result = result * PRIME + ($filePath == null ? 43 : $filePath.hashCode());
        return result;
    }

    @Override
    @SuppressWarnings("all")
    public String toString() {
        return "InstallData(path=" + this.getPath() + ", filePath=" + this.getFilePath() + ")";
    }
}
