// Generated by delombok at Sat Jul 14 04:26:21 CEST 2018
/*
 * SK's Minecraft Launcher
 * Copyright (C) 2010-2014 Albert Pham <http://www.sk89q.com> and contributors
 * Please see LICENSE.txt for license information.
 */
package com.skcraft.launcher.model.minecraft

import com.skcraft.launcher.util.Environment
import com.skcraft.launcher.util.Platform
import kotlinx.serialization.Encoder
import kotlinx.serialization.KSerializer
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.Serializer
import kotlinx.serialization.Transient
import kotlinx.serialization.builtins.MapSerializer
import kotlinx.serialization.builtins.list
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.list
import kotlinx.serialization.serializer
import java.util.regex.Pattern

@Serializable
data class Library(
    val name: String
) {
    @Serializer(forClass = Library::class)
    companion object : KSerializer<Library> {
        override fun serialize(encoder: Encoder, obj: Library) {
            val elemOutput = encoder.beginStructure(descriptor)
            elemOutput.encodeStringElement(descriptor, 0, obj.name)
            obj.baseUrl?.let { url ->
                elemOutput.encodeStringElement(descriptor, 1, url)
            }
            obj.natives?.let { natives ->
                elemOutput.encodeSerializableElement(
                    descriptor,
                    2,
                    MapSerializer(String.serializer(), String.serializer()),
                    natives
                )
            }
            obj.extract?.let { extract ->
                elemOutput.encodeSerializableElement(descriptor, 3, Extract.serializer(), extract)
            }
            obj.rules?.filter {
                it.action != null || it.os != null
            }?.let { rules ->
                elemOutput.encodeSerializableElement(descriptor, 4, Rule.serializer().list, rules)
            }
            elemOutput.endStructure(descriptor)
        }

        fun String.split() =
            this.split(":".toRegex()).dropLastWhile { it.isEmpty() }.toTypedArray()
    }

    @kotlin.jvm.Transient
    @Transient
    var group: String = name.split()[0]
    @kotlin.jvm.Transient
    @Transient
    var artifact: String? = name.split()[1]
    @kotlin.jvm.Transient
    @Transient
    var version: String? = name.split()[2]
    @SerialName("url")

    var baseUrl: String? = null

    var natives: Map<String, String>? = null

    var extract: Extract? = null

    var rules: List<Rule>? = null
    // Forge-added

    @Transient
    var comment: String? = null
    // Custom

    @Transient
    var isLocallyAvailable: Boolean = false

    fun matches(environment: Environment): Boolean {
        var allow = false
        if (rules != null) {
            for (rule in rules!!) {
                if (rule.matches(environment)) {
                    allow = rule.action == Action.allow
                }
            }
        } else {
            allow = true
        }
        return allow
    }

    fun getNativeString(platform: Platform): String? {
        return if (natives != null) {
            when (platform) {
                Platform.LINUX -> natives!!["linux"]

                Platform.WINDOWS -> natives!!["windows"]

                Platform.MAC_OS_X -> natives!!["osx"]

                else -> null
            }
        } else {
            null
        }
    }

    fun getFilename(environment: Environment): String {
        val nativeString = getNativeString(environment.platform)
        return if (nativeString != null) {
            String.format("%s-%s-%s.jar", artifact, version, nativeString)
        } else String.format("%s-%s.jar", artifact, version)
    }

    fun getPath(environment: Environment): String = buildString {
        append(group.replace('.', '/'))
        append("/")
        append(artifact)
        append("/")
        append(version)
        append("/")
        append(getFilename(environment))
    }.replace("\${arch}", environment.archBits)

    @Serializable
    data class Rule(
        var action: Action? = null,
        var os: OS? = null
    ) {
        fun matches(environment: Environment): Boolean {
            return if (os == null) {
                true
            } else {
                os!!.matches(environment)
            }
        }
    }

    @Serializable
    data class OS(
        var name: String? = null,
        var platform: Platform? = null,
        @Serializable(with = PatternSerializer::class)
        var version: Pattern? = null
    ) {
        fun matches(environment: Environment): Boolean {
            return (platform == null || platform == environment.platform) && version?.matcher(
                environment.platformVersion
            )?.matches() ?: true
        }

        @Serializer(forClass = OS::class)
        companion object : KSerializer<OS> {
            override fun serialize(encoder: Encoder, obj: OS) {
                val elemOutput = encoder.beginStructure(descriptor)
                obj.name?.let {
                    elemOutput.encodeStringElement(descriptor, 0, it)
                }
                obj.platform?.let { platform ->
                    elemOutput.encodeSerializableElement(descriptor, 1, Platform.serializer(), platform)
                }
                obj.version?.let { version ->
                    elemOutput.encodeSerializableElement(descriptor, 2, PatternSerializer, version)
                }
                elemOutput.endStructure(descriptor)
            }
        }
    }

    @Serializable
    data class Extract(
        var exclude: List<String>
    )

    enum class Action {
        allow, disallow;
    }
}
