// Generated by delombok at Sat Jul 14 04:26:21 CEST 2018
/*
 * SK's Minecraft Launcher
 * Copyright (C) 2010-2014 Albert Pham <http://www.sk89q.com> and contributors
 * Please see LICENSE.txt for license information.
 */
package newformat

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.Transient

@Serializable
data class FileInstall(
    var version: String? = null,
    var hash: String,
    var location: String,
    var to: String,

    var size: Long = 0,
    @SerialName("userFile")
    var isUserFile: Boolean = false,

//    var manifest: Manifest? = null,
    @SerialName("when")
    var conditionWhen: Condition? = null
) {
    // TODO: add extract type ?
    //  when do we extract / overwrite then ?
    val type: String = "file"

    // alias for "to"
    @Transient
    val targetPath: String
        get() = this.to
}
