// Generated by delombok at Sat Jul 14 01:46:55 CEST 2018
/*
 * SK's Minecraft Launcher
 * Copyright (C) 2010-2014 Albert Pham <http://www.sk89q.com> and contributors
 * Please see LICENSE.txt for license information.
 */
package newformat.builder

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import newformat.modpack.Feature

@Serializable
data class FeaturePattern(
    @SerialName("properties")
    var feature: Feature,
    @SerialName("files")
    var filePatterns: FnPatternList
) {
    fun matches(path: String): Boolean {
        return filePatterns.matches(path)
    }

//    @Serializer(forClass = FeaturePattern::class)
//    companion object {
//        override fun serialize(encoder: Encoder, obj: FeaturePattern) {
//            val elemOutput = encoder.beginStructure(descriptor)
//            elemOutput.encodeSerializableElement(descriptor, 0, Feature.Companion, obj.feature)
//            elemOutput.encodeSerializableElement(descriptor, 1, FnPatternList.Companion, obj.filePatterns)
//            elemOutput.endStructure(descriptor)
//        }
//    }
}
