// Generated by delombok at Sat Jul 14 01:46:55 CEST 2018
/*
 * SK's Minecraft Launcher
 * Copyright (C) 2010-2014 Albert Pham <http://www.sk89q.com> and contributors
 * Please see LICENSE.txt for license information.
 */
package com.skcraft.launcher.builder

import kotlinx.serialization.KOutput
import kotlinx.serialization.Optional
import kotlinx.serialization.Serializable
import kotlinx.serialization.Serializer
import kotlinx.serialization.Transient
import kotlinx.serialization.list
import kotlinx.serialization.serializer
import java.util.EnumSet

@Serializable
data class FnPatternList(
    @Optional
    var include: List<String> = arrayListOf(),
    @Optional
    var exclude: List<String> = arrayListOf(),
    @Transient
    var flags: EnumSet<FnMatch.Flag> = DEFAULT_FLAGS
) {

    fun matches(path: String): Boolean {
        return matches(path, this.include) && !matches(path, this.exclude)
    }

    private fun matches(path: String, patterns: Collection<String>): Boolean {
        for (pattern in patterns) {
            if (FnMatch.match(pattern = pattern, string = path, flags = flags)) {
                return true
            }
        }
        return false
    }

    @Serializer(forClass = FnPatternList::class)
    companion object {
        override fun save(output: KOutput, obj: FnPatternList) {
            val elemOutput = output.writeBegin(serialClassDesc)
            obj.include.takeUnless { it.isEmpty() }?.let {
                elemOutput.writeSerializableElementValue(serialClassDesc, 0, String.serializer().list, it)
            }
            obj.exclude.takeUnless { it.isEmpty() }?.let {
                elemOutput.writeSerializableElementValue(serialClassDesc, 1, String.serializer().list, it)
            }

            elemOutput.writeEnd(serialClassDesc)
        }

        private val DEFAULT_FLAGS = EnumSet.of<FnMatch.Flag>(FnMatch.Flag.CASEFOLD, FnMatch.Flag.PERIOD)
    }
}
