// Generated by delombok at Sat Jul 14 01:46:55 CEST 2018
/*
 * SK's Minecraft Launcher
 * Copyright (C) 2010-2014 Albert Pham <http://www.sk89q.com> and contributors
 * Please see LICENSE.txt for license information.
 */
package com.skcraft.launcher.builder

import kotlinx.serialization.Optional
import kotlinx.serialization.Serializable
import kotlinx.serialization.Transient
import java.util.EnumSet

@Serializable
data class FnPatternList(

    var include: List<String> = arrayListOf(),

    var exclude: List<String> = arrayListOf(),
    @Transient
    var flags: EnumSet<FnMatch.Flag> = DEFAULT_FLAGS
) {

    fun matches(path: String): Boolean {
        return matches(path, this.include) && !matches(path, this.exclude)
    }

    private fun matches(path: String, patterns: Collection<String>): Boolean {
        for (pattern in patterns) {
            if (FnMatch.match(pattern = pattern, string = path, flags = flags)) {
                return true
            }
        }
        return false
    }

    companion object {
        private val DEFAULT_FLAGS = EnumSet.of<FnMatch.Flag>(FnMatch.Flag.CASEFOLD, FnMatch.Flag.PERIOD)
    }
}
