// Generated by delombok at Sat Jul 14 04:26:21 CEST 2018
/*
 * SK's Minecraft Launcher
 * Copyright (C) 2010-2014 Albert Pham <http://www.sk89q.com> and contributors
 * Please see LICENSE.txt for license information.
 */
package com.skcraft.launcher.model.modpack

import com.skcraft.launcher.builder.FnPatternList
import kotlinx.serialization.Encoder
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Optional
import kotlinx.serialization.Serializable
import kotlinx.serialization.Serializer
import kotlinx.serialization.internal.EnumSerializer

@Serializable
data class Feature(
    @Optional var name: String = "", // use displayName from entry by default
    @Optional var selected: Boolean = false,
    @Optional var description: String = "", //TODO, use description from entry
    @Optional var recommendation: Recommendation? = null,
    @Optional
    @Serializable(with = FnPatternList.Companion::class)
    var files: FnPatternList = FnPatternList()
)
