// Generated by delombok at Sat Jul 14 01:46:55 CEST 2018
/*
 * SK's Minecraft Launcher
 * Copyright (C) 2010-2014 Albert Pham <http://www.sk89q.com> and contributors
 * Please see LICENSE.txt for license information.
 */
package com.skcraft.launcher.builder

import com.fasterxml.jackson.annotation.JsonProperty
import com.skcraft.launcher.model.modpack.Feature

class FeaturePattern(
        @JsonProperty("properties")
        var feature: Feature,
        @JsonProperty("files")
        var filePatterns: FnPatternList
) {

    fun matches(path: String): Boolean {
        return filePatterns.matches(path)
    }

    override fun equals(other: Any?): Boolean {
        if (other === this) return true
        if (other !is FeaturePattern) return false
        if (!other.canEqual(this as Any)) return false
        if (this.feature != other.feature) return false
        return this.filePatterns == other.filePatterns
    }

    private fun canEqual(other: Any): Boolean {
        return other is FeaturePattern
    }

    override fun hashCode(): Int {
        val PRIME = 59
        var result = 1
        result = result * PRIME + (this.feature.hashCode())
        result = result * PRIME + (this.filePatterns.hashCode() )
        return result
    }

    override fun toString(): String {
        return "FeaturePattern(feature=" + this.feature + ", filePatterns=" + this.filePatterns + ")"
    }
}
