// Generated by delombok at Sat Jul 14 01:46:55 CEST 2018
/*
 * SK's Minecraft Launcher
 * Copyright (C) 2010-2014 Albert Pham <http://www.sk89q.com> and contributors
 * Please see LICENSE.txt for license information.
 */
package com.skcraft.launcher.builder

import com.skcraft.launcher.model.modpack.Feature
import kotlinx.serialization.Optional
import kotlinx.serialization.Serializable

@Serializable
class FileInfo(
    @Optional
    var feature: Feature? = null
) {

    override fun equals(other: Any?): Boolean {
        if (other === this) return true
        if (other !is FileInfo) return false
        if (!other.canEqual(this as Any)) return false
        return this.feature == other.feature
    }

    private fun canEqual(other: Any): Boolean {
        return other is FileInfo
    }

    override fun hashCode(): Int {
        val PRIME = 59
        var result = 1
        result = result * PRIME + (feature?.hashCode() ?: 43)
        return result
    }

    override fun toString(): String {
        return "FileInfo(feature=" + this.feature + ")"
    }
}
