// Generated by delombok at Sat Jul 14 01:46:55 CEST 2018
/*
 * SK's Minecraft Launcher
 * Copyright (C) 2010-2014 Albert Pham <http://www.sk89q.com> and contributors
 * Please see LICENSE.txt for license information.
 */
package com.skcraft.launcher.builder

import com.beust.jcommander.JCommander
import com.google.common.io.Files
import com.skcraft.launcher.util.SimpleLogFormatter
import java.io.File
import java.io.IOException

class ServerCopyExport(private val destDir: File) : DirectoryWalker() {

    init {
    }

    override fun getBehavior(name: String): DirectoryWalker.DirectoryBehavior {
        return if (name.startsWith(".")) {
            DirectoryWalker.DirectoryBehavior.SKIP
        } else if (name == "_SERVER") {
            DirectoryWalker.DirectoryBehavior.IGNORE
        } else if (name == "_CLIENT") {
            DirectoryWalker.DirectoryBehavior.SKIP
        } else {
            DirectoryWalker.DirectoryBehavior.CONTINUE
        }
    }

    @Throws(IOException::class)
    override fun onFile(file: File, relPath: String) {
        val dest = File(destDir, relPath)
        log.info("Copying " + file.absolutePath + " to " + dest.absolutePath)
        dest.parentFile.mkdirs()
        Files.copy(file, dest)
    }

    companion object {
        private val log = java.util.logging.Logger.getLogger(ServerCopyExport::class.java.name)

        @Throws(IOException::class)
        @JvmStatic
        fun main(args: Array<String>) {
            SimpleLogFormatter.configureGlobalLogger()
            val options = ServerExportOptions()
            JCommander(options, *args)
            log.info("From: " + options.sourceDir!!.absolutePath)
            log.info("To: " + options.destDir!!.absolutePath)
            val task = ServerCopyExport(options.destDir!!)
            task.walk(options.sourceDir!!)
        }
    }
}
