package $PACKAGE
const val MAJOR_VERSION = $MAJOR_VERSION
const val MINOR_VERSION = $MINOR_VERSION
const val PATCH_VERSION = $PATCH_VERSION

const val VERSION = "$MAJOR_VERSION.$MINOR_VERSION.$PATCH_VERSION"