#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
java -jar $DIR/wrapper/wrapper.jar $@

if test -f "$DIR/wrapper/new.jar"; then
    mv $DIR/wrapper/new.jar $DIR/wrapper/wrapper.jar
fi