// Generated by delombok at Sat Jul 14 04:26:21 CEST 2018
/*
 * SK's Minecraft Launcher
 * Copyright (C) 2010-2014 Albert Pham <http://www.sk89q.com> and contributors
 * Please see LICENSE.txt for license information.
 */
package com.skcraft.launcher.model.modpack

import com.fasterxml.jackson.annotation.JsonIgnore
import com.google.common.hash.Hashing

import com.google.common.base.Preconditions.checkNotNull

class FileInstall(
        var version: String? = null,
        var hash: String? = null,
        var location: String? = null,
        var to: String? = null,
        var size: Long = 0,
        var isUserFile: Boolean = false
) : ManifestEntry() {
    

    val impliedVersion: String
        @JsonIgnore
        get() = checkNotNull<String>(if (version != null) version else hash)

    val targetPath: String
        @JsonIgnore
        get() = checkNotNull<String>(if (this.to != null) this.to else location)

    override fun toString(): String {
        return "FileInstall(version=" + this.version + ", hash=" + this.hash + ", location=" + this.location + ", to=" + this.to + ", size=" + this.size + ", userFile=" + this.isUserFile + ")"
    }

    override fun equals(other: Any?): Boolean {
        if (other === this) return true
        if (other !is FileInstall) return false
        if (!other.canEqual(this as Any)) return false
        if (if (this.version == null) other.version != null else this.version != other.version) return false
        if (if (this.hash == null) other.hash != null else this.hash != other.hash) return false
        if (if (this.location == null) other.location != null else this.location != other.location) return false
        if (if (this.to == null) other.to != null else this.to != other.to) return false
        if (this.size != other.size) return false
        return this.isUserFile == other.isUserFile
    }

    override fun canEqual(other: Any): Boolean {
        return other is FileInstall
    }

    override fun hashCode(): Int {
        val PRIME = 59
        var result = 1
        result = result * PRIME + (version?.hashCode() ?: 43)
        result = result * PRIME + (hash?.hashCode() ?: 43)
        result = result * PRIME + (location?.hashCode() ?: 43)
        result = result * PRIME + (to?.hashCode() ?: 43)
        result = result * PRIME + (size.ushr(32) xor size).toInt()
        result = result * PRIME + if (this.isUserFile) 79 else 97
        return result
    }

    companion object {
        private val hf = Hashing.sha1()
    }
}
