// Generated by delombok at Sat Jul 14 04:26:21 CEST 2018
/*
 * SK's Minecraft Launcher
 * Copyright (C) 2010-2014 Albert Pham <http://www.sk89q.com> and contributors
 * Please see LICENSE.txt for license information.
 */
package com.skcraft.launcher.model.modpack;

import java.util.ArrayList;
import java.util.List;

public class LaunchModifier {
    private List<String> flags = new ArrayList<>();

    @SuppressWarnings("all")
    public LaunchModifier() {
    }

    @SuppressWarnings("all")
    public List<String> getFlags() {
        return this.flags;
    }

    @Override
    @SuppressWarnings("all")
    public boolean equals(final Object o) {
        if (o == this) return true;
        if (!(o instanceof LaunchModifier)) return false;
        final LaunchModifier other = (LaunchModifier) o;
        if (!other.canEqual((Object) this)) return false;
        final Object this$flags = this.getFlags();
        final Object other$flags = other.getFlags();
        if (this$flags == null ? other$flags != null : !this$flags.equals(other$flags)) return false;
        return true;
    }

    @SuppressWarnings("all")
    protected boolean canEqual(final Object other) {
        return other instanceof LaunchModifier;
    }

    @Override
    @SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final Object $flags = this.getFlags();
        result = result * PRIME + ($flags == null ? 43 : $flags.hashCode());
        return result;
    }

    @Override
    @SuppressWarnings("all")
    public String toString() {
        return "LaunchModifier(flags=" + this.getFlags() + ")";
    }
}
