// Generated by delombok at Sat Jul 14 04:26:21 CEST 2018
/*
 * SK's Minecraft Launcher
 * Copyright (C) 2010-2014 Albert Pham <http://www.sk89q.com> and contributors
 * Please see LICENSE.txt for license information.
 */
package com.skcraft.launcher.model.modpack

import com.fasterxml.jackson.annotation.JsonCreator
import com.fasterxml.jackson.annotation.JsonIdentityInfo
import com.fasterxml.jackson.annotation.JsonValue
import com.fasterxml.jackson.annotation.ObjectIdGenerators

@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator::class, property = "name")
class Feature(val name: String,
              val description: String,
              val selected: Boolean) : Comparable<Feature> {
    var recommendation: Recommendation? = null

    enum class Recommendation {
        STARRED, AVOID;

        @JsonValue
        fun toJson(): String {
            return name.toLowerCase()
        }

        companion object {

            @JsonCreator
            fun fromJson(text: String): Recommendation {
                return valueOf(text.toUpperCase())
            }
        }
    }

    override fun compareTo(other: Feature): Int = name.compareTo(other.name)
}
