// Generated by delombok at Sat Jul 14 04:26:21 CEST 2018
/*
 * SK's Minecraft Launcher
 * Copyright (C) 2010-2014 Albert Pham <http://www.sk89q.com> and contributors
 * Please see LICENSE.txt for license information.
 */
package com.skcraft.launcher.model.modpack

import com.fasterxml.jackson.annotation.JsonCreator
import com.fasterxml.jackson.annotation.JsonValue
import kotlinx.serialization.Optional
import kotlinx.serialization.Serializable

@Serializable
class Feature(
    val name: String,
    val description: String,
    val selected: Boolean,
    @Optional var recommendation: Recommendation? = null
) : Comparable<Feature> {

    enum class Recommendation {
        STARRED, AVOID;

        @JsonValue
        fun toJson(): String {
            return name.toLowerCase()
        }

        companion object {

            @JsonCreator
            fun fromJson(text: String): Recommendation {
                return valueOf(text.toUpperCase())
            }
        }
    }

    override fun compareTo(other: Feature): Int = name.compareTo(other.name)
}
