// Generated by delombok at Sat Jul 14 04:26:21 CEST 2018
/*
 * SK's Minecraft Launcher
 * Copyright (C) 2010-2014 Albert Pham <http://www.sk89q.com> and contributors
 * Please see LICENSE.txt for license information.
 */
package com.skcraft.launcher.model.modpack

import kotlinx.serialization.KOutput
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.Serializer
import kotlinx.serialization.internal.EnumSerializer

@Serializable
data class Feature(
    val name: String,
    val description: String,
    val selected: Boolean,
//    @Optional
    var recommendation: Recommendation? = null
) {

    @Serializer(forClass = Feature::class)
    companion object : KSerializer<Feature> {
        override fun save(output: KOutput, obj: Feature) {
            val elemOutput = output.writeBegin(serialClassDesc)
            elemOutput.writeStringElementValue(serialClassDesc, 0, obj.name)
            elemOutput.writeStringElementValue(serialClassDesc, 1, obj.description)
            if (obj.selected) elemOutput.writeBooleanElementValue(serialClassDesc, 2, obj.selected)
            obj.recommendation?.let { recommendation ->
                elemOutput.writeElement(serialClassDesc, 3)
                elemOutput.write(EnumSerializer(Recommendation::class), recommendation)
            }
            elemOutput.writeEnd(serialClassDesc)
        }
    }
}
