// Generated by delombok at Sat Jul 14 04:26:21 CEST 2018
/*
 * SK's Minecraft Launcher
 * Copyright (C) 2010-2014 Albert Pham <http://www.sk89q.com> and contributors
 * Please see LICENSE.txt for license information.
 */
package com.skcraft.launcher.model.modpack

import kotlinx.serialization.KOutput
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Optional
import kotlinx.serialization.Serializable
import kotlinx.serialization.Serializer
import kotlinx.serialization.Transient
import kotlinx.serialization.list
import kotlinx.serialization.serializer
import voodoo.data.UserFiles
import voodoo.data.flat.ModPack
import voodoo.data.sk.Launch

@Serializable
data class FileInstall(
    @Optional var version: String? = null,
    var hash: String,
    var location: String,
    var to: String,
    @Optional var size: Long = 0,
    @Optional var isUserFile: Boolean = false
) : ManifestEntry() {
    @Transient
    val targetPath: String
        get() = this.to

    @Serializer(forClass = FileInstall::class)
    companion object : KSerializer<FileInstall> {
        override fun save(output: KOutput, obj: FileInstall) {
            val elemOutput = output.writeBegin(serialClassDesc)
            obj.version?.let { version ->
                elemOutput.writeStringElementValue(serialClassDesc, 0, version)
            }
            elemOutput.writeStringElementValue(serialClassDesc, 1, obj.hash)
            elemOutput.writeStringElementValue(serialClassDesc, 2, obj.location)
            elemOutput.writeStringElementValue(serialClassDesc, 3, obj.to)
            if (obj.size != 0L) elemOutput.writeLongElementValue(serialClassDesc, 4, obj.size)
            elemOutput.writeBooleanElementValue(serialClassDesc, 5, obj.isUserFile)
            elemOutput.writeEnd(serialClassDesc)
        }
    }
}
