// Generated by delombok at Sat Jul 14 05:49:42 CEST 2018
/*
 * SK's Minecraft Launcher
 * Copyright (C) 2010-2014 Albert Pham <http://www.sk89q.com> and contributors
 * Please see LICENSE.txt for license information.
 */
package com.skcraft.launcher.model.modpack

import com.fasterxml.jackson.annotation.JsonManagedReference
import com.fasterxml.jackson.annotation.JsonProperty
import com.skcraft.launcher.model.minecraft.VersionManifest
import java.net.URL

class Manifest(
        var minimumVersion: Int = 0
) : BaseManifest() {

    var baseUrl: URL? = null
    var librariesLocation: String? = null
    var objectsLocation: String? = null
    var gameVersion: String? = null
    @JsonProperty("launch")
    var launchModifier: LaunchModifier? = null
    var features: List<Feature>? = emptyList()
    @JsonManagedReference("manifest")
    var tasks: MutableList<ManifestEntry> = mutableListOf()
    var versionManifest: VersionManifest? = null

    fun updateName(name: String?) {
        if (name != null) {
            super.name = name
        }
    }

    fun updateTitle(title: String?) {
        if (title != null) {
            super.title = title
        }
    }

    fun updateGameVersion(gameVersion: String?) {
        if (gameVersion != null) {
            this.gameVersion = gameVersion
        }
    }

    companion object {
        val MIN_PROTOCOL_VERSION = 2
    }
}
