// Generated by delombok at Sat Jul 14 05:49:42 CEST 2018
/*
 * SK's Minecraft Launcher
 * Copyright (C) 2010-2014 Albert Pham <http://www.sk89q.com> and contributors
 * Please see LICENSE.txt for license information.
 */
package com.skcraft.launcher.model.modpack

import com.skcraft.launcher.model.minecraft.VersionManifest
import kotlinx.serialization.Optional
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import java.net.URL

@Serializable
class Manifest(
        var minimumVersion: Int = 0
) : BaseManifest() {
    @Optional var baseUrl: URL? = null
    @Optional var librariesLocation: String? = null
    @Optional var objectsLocation: String? = null
    @Optional var gameVersion: String? = null
    @SerialName("launch")
    @Optional var launchModifier: LaunchModifier? = null
    @Optional var features: List<Feature>? = emptyList()
//    @JsonManagedReference("manifest")
    @Optional var tasks: MutableList<ManifestEntry> = mutableListOf()
    @Optional var versionManifest: VersionManifest? = null

    fun updateName(name: String?) {
        if (name != null) {
            super.name = name
        }
    }

    fun updateTitle(title: String?) {
        if (title != null) {
            super.title = title
        }
    }

    fun updateGameVersion(gameVersion: String?) {
        if (gameVersion != null) {
            this.gameVersion = gameVersion
        }
    }

    companion object {
        val MIN_PROTOCOL_VERSION = 2
    }
}
