// Generated by delombok at Sat Jul 14 04:26:21 CEST 2018
/*
 * SK's Minecraft Launcher
 * Copyright (C) 2010-2014 Albert Pham <http://www.sk89q.com> and contributors
 * Please see LICENSE.txt for license information.
 */
package com.skcraft.launcher.model.minecraft

import com.skcraft.launcher.util.Environment
import com.skcraft.launcher.util.Platform
import kotlinx.serialization.Optional
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import java.util.regex.Pattern
import kotlinx.serialization.Transient

@Serializable
data class Library(
    val name: String
) {
    companion object {
        fun String.split() =
            this.split(":".toRegex()).dropLastWhile { it.isEmpty() }.toTypedArray()
    }

    @kotlin.jvm.Transient
    @Transient
    var group: String = name.split()[0]
    @kotlin.jvm.Transient
    @Transient
    var artifact: String? = name.split()[1]
    @kotlin.jvm.Transient
    @Transient
    var version: String? = name.split()[2]
    @SerialName("url")
    @Optional
    var baseUrl: String? = null
    @Optional
    var natives: Map<String, String>? = null
    @Optional
    var extract: Extract? = null
    @Optional
    var rules: List<Rule>? = null
    // Forge-added
    @Optional
    var comment: String? = null
    // Custom
    @Optional
    var isLocallyAvailable: Boolean = false

    fun matches(environment: Environment): Boolean {
        var allow = false
        if (rules != null) {
            for (rule in rules!!) {
                if (rule.matches(environment)) {
                    allow = rule.action == Action.allow
                }
            }
        } else {
            allow = true
        }
        return allow
    }

    fun getNativeString(platform: Platform): String? {
        return if (natives != null) {
            when (platform) {
                Platform.LINUX -> natives!!["linux"]

                Platform.WINDOWS -> natives!!["windows"]

                Platform.MAC_OS_X -> natives!!["osx"]

                else -> null
            }
        } else {
            null
        }
    }

    fun getFilename(environment: Environment): String {
        val nativeString = getNativeString(environment.platform)
        return if (nativeString != null) {
            String.format("%s-%s-%s.jar", artifact, version, nativeString)
        } else String.format("%s-%s.jar", artifact, version)
    }

    fun getPath(environment: Environment): String {
        val builder = StringBuilder()
        builder.append(group.replace('.', '/'))
        builder.append("/")
        builder.append(artifact)
        builder.append("/")
        builder.append(version)
        builder.append("/")
        builder.append(getFilename(environment))
        var path = builder.toString()
        path = path.replace("\${arch}", environment.archBits)
        return path
    }

    @Serializable
    data class Rule(
        @Optional
        var action: Action? = null,
        @Optional
        var os: OS? = null
    ) {

        fun matches(environment: Environment): Boolean {
            return if (os == null) {
                true
            } else {
                os!!.matches(environment)
            }
        }
    }

    @Serializable
    data class OS(
        @Optional var platform: Platform? = null,
        @Optional var version: Pattern? = null
    ) {
        fun matches(environment: Environment): Boolean {
            return (platform == null || platform == environment.platform) && (version == null || version!!.matcher(
                environment.platformVersion
            ).matches())
        }
    }

    @Serializable
    data class Extract(
        var exclude: List<String>
    )

    enum class Action {
        allow, disallow;

        fun toJson(): String {
            return name.toLowerCase()
        }

        companion object {

            fun fromJson(text: String): Action {
                return valueOf(text.toUpperCase())
            }
        }
    }

    override fun toString(): String {
        return "Library(name=" + this.name + ", group=" + this.group + ", artifact=" + this.artifact + ", version=" + this.version + ", baseUrl=" + this.baseUrl + ", natives=" + this.natives + ", extract=" + this.extract + ", rules=" + this.rules + ", comment=" + this.comment + ", locallyAvailable=" + this.isLocallyAvailable + ")"
    }
}
