// Generated by delombok at Sat Jul 14 01:46:55 CEST 2018
/*
 * SK's Minecraft Launcher
 * Copyright (C) 2010-2014 Albert Pham <http://www.sk89q.com> and contributors
 * Please see LICENSE.txt for license information.
 */
package com.skcraft.launcher.builder;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.skcraft.launcher.model.modpack.Feature;

public class FeaturePattern {
    @JsonProperty("properties")
    private Feature feature;
    @JsonProperty("files")
    private FnPatternList filePatterns = new FnPatternList();

    public boolean matches(String path) {
        return filePatterns != null && filePatterns.matches(path);
    }

    @java.lang.SuppressWarnings("all")
    public FeaturePattern() {
    }

    @java.lang.SuppressWarnings("all")
    public Feature getFeature() {
        return this.feature;
    }

    @java.lang.SuppressWarnings("all")
    public FnPatternList getFilePatterns() {
        return this.filePatterns;
    }

    @java.lang.SuppressWarnings("all")
    public void setFeature(final Feature feature) {
        this.feature = feature;
    }

    @java.lang.SuppressWarnings("all")
    public void setFilePatterns(final FnPatternList filePatterns) {
        this.filePatterns = filePatterns;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof FeaturePattern)) return false;
        final FeaturePattern other = (FeaturePattern) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$feature = this.getFeature();
        final java.lang.Object other$feature = other.getFeature();
        if (this$feature == null ? other$feature != null : !this$feature.equals(other$feature)) return false;
        final java.lang.Object this$filePatterns = this.getFilePatterns();
        final java.lang.Object other$filePatterns = other.getFilePatterns();
        if (this$filePatterns == null ? other$filePatterns != null : !this$filePatterns.equals(other$filePatterns)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof FeaturePattern;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $feature = this.getFeature();
        result = result * PRIME + ($feature == null ? 43 : $feature.hashCode());
        final java.lang.Object $filePatterns = this.getFilePatterns();
        result = result * PRIME + ($filePatterns == null ? 43 : $filePatterns.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "FeaturePattern(feature=" + this.getFeature() + ", filePatterns=" + this.getFilePatterns() + ")";
    }
}
