// Generated by delombok at Sat Jul 14 01:46:55 CEST 2018
/*
 * SK's Minecraft Launcher
 * Copyright (C) 2010-2014 Albert Pham <http://www.sk89q.com> and contributors
 * Please see LICENSE.txt for license information.
 */
package com.skcraft.launcher.builder;

import com.beust.jcommander.Parameter;
import java.io.File;

public class ServerExportOptions {
    @Parameter(names = "--source", required = true)
    private File sourceDir;
    @Parameter(names = "--dest", required = true)
    private File destDir;

    @java.lang.SuppressWarnings("all")
    public ServerExportOptions() {
    }

    @java.lang.SuppressWarnings("all")
    public File getSourceDir() {
        return this.sourceDir;
    }

    @java.lang.SuppressWarnings("all")
    public File getDestDir() {
        return this.destDir;
    }

    @java.lang.SuppressWarnings("all")
    public void setSourceDir(final File sourceDir) {
        this.sourceDir = sourceDir;
    }

    @java.lang.SuppressWarnings("all")
    public void setDestDir(final File destDir) {
        this.destDir = destDir;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ServerExportOptions)) return false;
        final ServerExportOptions other = (ServerExportOptions) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$sourceDir = this.getSourceDir();
        final java.lang.Object other$sourceDir = other.getSourceDir();
        if (this$sourceDir == null ? other$sourceDir != null : !this$sourceDir.equals(other$sourceDir)) return false;
        final java.lang.Object this$destDir = this.getDestDir();
        final java.lang.Object other$destDir = other.getDestDir();
        if (this$destDir == null ? other$destDir != null : !this$destDir.equals(other$destDir)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ServerExportOptions;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $sourceDir = this.getSourceDir();
        result = result * PRIME + ($sourceDir == null ? 43 : $sourceDir.hashCode());
        final java.lang.Object $destDir = this.getDestDir();
        result = result * PRIME + ($destDir == null ? 43 : $destDir.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "ServerExportOptions(sourceDir=" + this.getSourceDir() + ", destDir=" + this.getDestDir() + ")";
    }
}
