package voodoo.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.requireObject
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.slf4j.MDCContext
import mu.KotlinLogging
import mu.withLoggingContext
import voodoo.util.maven.MavenUtil
import voodoo.voodoo.GeneratedConstants
import java.io.StringWriter
import java.util.*

class UpdateCommand : CliktCommand(
    name = "update",
    help = "updates the version of voodoo"
) {
    private val logger = KotlinLogging.logger {}
    val cliContext by requireObject<CLIContext>()

    override fun run(): Unit = withLoggingContext("command" to commandName) {
        val rootDir = cliContext.rootDir

        runBlocking(MDCContext()) {
            val propertiesFile = rootDir.resolve("wrapper/wrapper.properties")
            propertiesFile.absoluteFile.parentFile.mkdirs()

            val properties = Properties().also { prop ->
                propertiesFile.bufferedReader().use {
                    prop.load(it)
                }
            }

            val version = MavenUtil.getLatestVersionFromMavenMetadata(
                GeneratedConstants.MAVEN_URL,
                GeneratedConstants.MAVEN_GROUP,
                "voodoo"
            )
            val groupPath = GeneratedConstants.MAVEN_GROUP.replace('.', '/')
            properties["distributionUrl"] =
                "${GeneratedConstants.MAVEN_URL}/$groupPath/voodoo/$version/voodoo-$version-${GeneratedConstants.MAVEN_SHADOW_CLASSIFIER}.jar"
//            prop["distributionPath"] = "wrapper/bin"

            StringWriter().use {
                properties.store(it, "generated by: voodoo generateWrapper")
                propertiesFile.writeText(it.toString())
            }
        }
    }
}