// Generated by delombok at Sat Jul 14 01:46:55 CEST 2018
/*
 * SK's Minecraft Launcher
 * Copyright (C) 2010-2014 Albert Pham <http://www.sk89q.com> and contributors
 * Please see LICENSE.txt for license information.
 */
package com.skcraft.launcher.builder;

import com.skcraft.launcher.model.modpack.Feature;

public class FileInfo {
    private Feature feature;

    @SuppressWarnings("all")
    public FileInfo() {
    }

    @SuppressWarnings("all")
    public Feature getFeature() {
        return this.feature;
    }

    @SuppressWarnings("all")
    public void setFeature(final Feature feature) {
        this.feature = feature;
    }

    @Override
    @SuppressWarnings("all")
    public boolean equals(final Object o) {
        if (o == this) return true;
        if (!(o instanceof FileInfo)) return false;
        final FileInfo other = (FileInfo) o;
        if (!other.canEqual((Object) this)) return false;
        final Object this$feature = this.getFeature();
        final Object other$feature = other.getFeature();
        if (this$feature == null ? other$feature != null : !this$feature.equals(other$feature)) return false;
        return true;
    }

    @SuppressWarnings("all")
    protected boolean canEqual(final Object other) {
        return other instanceof FileInfo;
    }

    @Override
    @SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final Object $feature = this.getFeature();
        result = result * PRIME + ($feature == null ? 43 : $feature.hashCode());
        return result;
    }

    @Override
    @SuppressWarnings("all")
    public String toString() {
        return "FileInfo(feature=" + this.getFeature() + ")";
    }
}
