// Generated by delombok at Sat Jul 14 04:26:21 CEST 2018
/*
 * SK's Minecraft Launcher
 * Copyright (C) 2010-2014 Albert Pham <http://www.sk89q.com> and contributors
 * Please see LICENSE.txt for license information.
 */
package com.skcraft.launcher.model.minecraft;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown = true)
public class Asset {
    private String hash;
    private int size;

    @SuppressWarnings("all")
    public Asset() {
    }

    @SuppressWarnings("all")
    public String getHash() {
        return this.hash;
    }

    @SuppressWarnings("all")
    public int getSize() {
        return this.size;
    }

    @SuppressWarnings("all")
    public void setHash(final String hash) {
        this.hash = hash;
    }

    @SuppressWarnings("all")
    public void setSize(final int size) {
        this.size = size;
    }

    @Override
    @SuppressWarnings("all")
    public boolean equals(final Object o) {
        if (o == this) return true;
        if (!(o instanceof Asset)) return false;
        final Asset other = (Asset) o;
        if (!other.canEqual((Object) this)) return false;
        final Object this$hash = this.getHash();
        final Object other$hash = other.getHash();
        if (this$hash == null ? other$hash != null : !this$hash.equals(other$hash)) return false;
        if (this.getSize() != other.getSize()) return false;
        return true;
    }

    @SuppressWarnings("all")
    protected boolean canEqual(final Object other) {
        return other instanceof Asset;
    }

    @Override
    @SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final Object $hash = this.getHash();
        result = result * PRIME + ($hash == null ? 43 : $hash.hashCode());
        result = result * PRIME + this.getSize();
        return result;
    }

    @Override
    @SuppressWarnings("all")
    public String toString() {
        return "Asset(hash=" + this.getHash() + ", size=" + this.getSize() + ")";
    }
}
